import { prisma } from '../src/lib/prisma.js'
import bcrypt from 'bcryptjs'

const storesData = [
  { id: "18", name: "Av. Portugal", address: "Av. Portugal, 1397", code:"PT" },
  { id: "20", name: "Henrique Dumont", address: "Rua Henrique Dumont, 1365", code:"HD" },
  { id: "16", name: "Tamandaré", address: "Rua Tamandaré, 977", code:"TM" },
  { id: "15", name: "Sertãozinho", address: "Rua Humberto Hortolan, 970", code:"ST" },
  { id: "17", name: "Nova Aliança", address: "Rua Professor Roberto José, 200", code:"NA" },
  { id: "14", name: "Jardim Botânico", address: "Av. Carlos Eduardo de Gasperi Consoni, 1392", code:"JB" },
  { id: "8", name: "San Marco", address: "Estr. da Limeirinha, 1350", code:"SM" },
  { id: "21", name: "Jardim Califórnia", address: "Av. Califórnia, 747", code:"CAL" },
  { id: "19", name: "Centro de Distribuição", address: "Av. Celso Daniel, 505", code: "CD" }
]

interface SeedProduct {
  name: string
  stockCD?: number | null
}

const productCategories: { category: string; products: SeedProduct[] }[] = [
  {
    category: "Frutas",
    products: [
      { name: "Abacate", stockCD: 14 },
      { name: "Abacaxi Gomo", stockCD: 0 },
      { name: "Abacaxi Hawai", stockCD: 0 },
      { name: "Abacaxi Perola", stockCD: 4390 },
      { name: "Abacaxi Perola Medio", stockCD: 0 },
      { name: "Abacaxi cx", stockCD: 0 },
      { name: "Abil", stockCD: 0 },
      { name: "Acerola", stockCD: 0 },
      { name: "Achachairu", stockCD: 0 },
      { name: "Agua Coco 1 Litro", stockCD: 0 },
      { name: "Agua Coco 500ml", stockCD: 0 },
      { name: "Ameixa Dagen", stockCD: 0 },
      { name: "Ameixa Dinossauro", stockCD: 0 },
      { name: "Ameixa Importada", stockCD: 4 },
      { name: "Ameixa Nacional 10kg - 2A", stockCD: 0 },
      { name: "Ameixa Nacional 10kg - 3A", stockCD: 0 },
      { name: "Ameixa Nacional 10kg - 4A", stockCD: 0 },
      { name: "Ameixa Nacional 6kg", stockCD: 0 },
      { name: "Ameixa Nacional 6kg Band", stockCD: 0 },
      { name: "Ameixa Sun Golden", stockCD: 0 },
      { name: "Ameixa USA", stockCD: 0 },
      { name: "Amora", stockCD: 0 },
      { name: "Amora Band", stockCD: 0 },
      { name: "Atemoia 4kg", stockCD: 0 },
      { name: "Atemoia 8kg", stockCD: 26 },
      { name: "Avocado", stockCD: 19 },
      { name: "Avocado 5kg", stockCD: 0 },
      { name: "Banana Fritar", stockCD: 6 },
      { name: "Banana Maça 15kg", stockCD: 4 },
      { name: "Banana Maça 20kg", stockCD: 0 },
      { name: "Banana Nanica 15kg", stockCD: 0 },
      { name: "Banana Nanica 20kg", stockCD: 10 },
      { name: "Banana Nanica Exportação", stockCD: 0 },
      { name: "Banana Organica (Prata)", stockCD: 0 },
      { name: "Banana Organica Nanica", stockCD: 0 },
      { name: "Banana Organica Prata", stockCD: 0 },
      { name: "Banana Ouro", stockCD: 0 },
      { name: "Banana Prata 15kg", stockCD: 30 },
      { name: "Banana Prata 20kg", stockCD: 0 },
      { name: "Banana Terra", stockCD: 3 },
      { name: "Banana Turma Monica (Nanica)", stockCD: 0 },
      { name: "Cacau", stockCD: 0 },
      { name: "Caju", stockCD: 0 },
      { name: "Cajamanga", stockCD: 0 },
      { name: "Caqui CP", stockCD: 0 },
      { name: "Caqui Chocolate/Kioto", stockCD: 0 },
      { name: "Caqui Fuiu", stockCD: 57 },
      { name: "Caqui Guiombo", stockCD: 0 },
      { name: "Caqui Rama Forte 10kg", stockCD: 0 },
      { name: "Caqui Rama Forte 12kg (c/20band)", stockCD: 0 },
      { name: "Caqui Rama Forte 6kg", stockCD: 0 },
      { name: "Carambola", stockCD: 16 },
      { name: "Carambola Band", stockCD: 0 },
      { name: "Caramoela", stockCD: 0 },
      { name: "Castanha Portuguesa", stockCD: 0 },
      { name: "Cereja Amarela 250gr c/46 (Trebeschi)", stockCD: 0 },
      { name: "Cereja Band.", stockCD: 0 },
      { name: "Cereja Importada", stockCD: 4 },
      { name: "Coco Seco", stockCD: 22 },
      { name: "Coco Verde", stockCD: 7600 },
      { name: "Cupuaçu", stockCD: 0 },
      { name: "Damasco", stockCD: 0 },
      { name: "Figo", stockCD: 49 },
      { name: "Figo da India", stockCD: 0 },
      { name: "Framboesa", stockCD: 0 },
      { name: "Fruta do Conde", stockCD: 0 },
      { name: "Goiaba Branca 10kg", stockCD: 0 },
      { name: "Goiaba Branca 2kg", stockCD: 0 },
      { name: "Goiaba Vermelha 10kg", stockCD: 32 },
      { name: "Goiaba Vermelha 12kg - GG", stockCD: 0 },
      { name: "Goiaba Vermelha 2kg", stockCD: 0 },
      { name: "Granadila", stockCD: 0 },
      { name: "Grape Fruit", stockCD: 0 },
      { name: "Graviola", stockCD: 0 },
      { name: "Groselha", stockCD: 0 },
      { name: "Jabuticaba", stockCD: 0 },
      { name: "Jaca", stockCD: 0 },
      { name: "Jambo", stockCD: 0 },
      { name: "Jurubeba", stockCD: 0 },
      { name: "Kinkan", stockCD: 0 },
      { name: "Kiwi Golden / Band.", stockCD: 9 },
      { name: "Kiwi Importado", stockCD: 33 },
      { name: "Kiwi Nacional", stockCD: 22 },
      { name: "Kiwi Nova Zelandia", stockCD: 0 },
      { name: "Lakio", stockCD: 0 },
      { name: "Laranja 7Kg saco", stockCD: 0 },
      { name: "Laranja Bahia Imp.", stockCD: 80 },
      { name: "Laranja Bahia Nac.", stockCD: 0 },
      { name: "Laranja Cara Cara", stockCD: 0 },
      { name: "Laranja Champanhe", stockCD: 0 },
      { name: "Laranja Lima", stockCD: 17 },
      { name: "Laranja Pera Rio", stockCD: 58 },
      { name: "Laranja Pera Rio Suco", stockCD: 0 },
      { name: "Laranja Selecta", stockCD: 0 },
      { name: "Lichia", stockCD: 0 },
      { name: "Lichia c/4", stockCD: 0 },
      { name: "Lima da Persia", stockCD: 4 },
      { name: "Lima da Persia 1/2", stockCD: 0 },
      { name: "Limão Cravo", stockCD: 15 },
      { name: "Limão Galego", stockCD: 0 },
      { name: "Limão Siciliano", stockCD: 6 },
      { name: "Limão Siciliano 1/2", stockCD: 0 },
      { name: "Limão Taithi", stockCD: 48 },
      { name: "Longan", stockCD: 0 },
      { name: "Maçã Argentina", stockCD: 123 },
      { name: "Maçã Argentina 1/2", stockCD: 0 },
      { name: "Maçã Fuji", stockCD: 113 },
      { name: "Maçã Fuji 1/2", stockCD: 0 },
      { name: "Maçã Fuji Miuda", stockCD: 33 },
      { name: "Maçã Gala", stockCD: 111 },
      { name: "Maçã Gala 1/2", stockCD: 0 },
      { name: "Maçã Gala Miuda", stockCD: 53 },
      { name: "Maçã Gransmith 1/2", stockCD: 0 },
      { name: "Maçã Pink Lady", stockCD: 65 },
      { name: "Maçã Sacolinha", stockCD: 0 },
      { name: "Maçã Verde Gransmith", stockCD: 43 },
      { name: "Mamão Formosa", stockCD: 0 },
      { name: "Mamão Formosa Exportação", stockCD: 137 },
      { name: "Mamão Papaia", stockCD: 29 },
      { name: "Mamão Papaia Belo", stockCD: 0 },
      { name: "Manga Borbom", stockCD: 0 },
      { name: "Manga Comum", stockCD: 0 },
      { name: "Manga Coquinho", stockCD: 0 },
      { name: "Manga Espada", stockCD: 0 },
      { name: "Manga Haden", stockCD: 0 },
      { name: "Manga Keit", stockCD: 0 },
      { name: "Manga Maça", stockCD: 0 },
      { name: "Manga Ouro", stockCD: 0 },
      { name: "Manga Palmer", stockCD: 0 },
      { name: "Manga Palmer 10kg", stockCD: 520 },
      { name: "Manga Palmer 18kg", stockCD: 0 },
      { name: "Manga Rosa", stockCD: 0 },
      { name: "Manga Sabina", stockCD: 0 },
      { name: "Manga Tomy", stockCD: 0 },
      { name: "Manga Tomy 10kg", stockCD: 0 },
      { name: "Manga Tomy 18kg", stockCD: 0 },
      { name: "Manga Vandaik", stockCD: 0 },
      { name: "Mangostim", stockCD: 0 },
      { name: "Maracuja Azedo", stockCD: 93 },
      { name: "Maracuja Azedo p/ Suco", stockCD: 0 },
      { name: "Maracuja Doce", stockCD: 0 },
      { name: "Melancia", stockCD: 0 },
      { name: "Melancia Polpa Amarela", stockCD: 0 },
      { name: "Melancia s/ Semente / Baby", stockCD: 0 },
      { name: "Melão Amarelo", stockCD: 207 },
      { name: "Melão Cantaloupe", stockCD: 0 },
      { name: "Melão Clarante", stockCD: 0 },
      { name: "Melão Dino", stockCD: 0 },
      { name: "Melão Espanhol", stockCD: 51 },
      { name: "Melão Espanhol Rei", stockCD: 0 },
      { name: "Melão Galia", stockCD: 0 },
      { name: "Melão Net", stockCD: 0 },
      { name: "Melão Orange", stockCD: 0 },
      { name: "Melão Rei - Original", stockCD: 171 },
      { name: "Melão Rei - Redinha (sp)", stockCD: 0 },
      { name: "Melão Salmão", stockCD: 0 },
      { name: "Mirtilho", stockCD: 40 },
      { name: "Mix Frutas Vermelhas", stockCD: 0 },
      { name: "Morango", stockCD: 0 },
      { name: "Morango Export.", stockCD: 0 },
      { name: "Morango Isopor c/2", stockCD: 0 },
      { name: "Morango Organico", stockCD: 0 },
      { name: "morango isopor hidroponico", stockCD: null },
      { name: "Nectarina Importada", stockCD: 0 },
      { name: "Nectarina Nacional 10kg - 2A", stockCD: 0 },
      { name: "Nectarina Nacional 10kg - 3A", stockCD: 0 },
      { name: "Nectarina Nacional 10kg - 4A", stockCD: 0 },
      { name: "Nectarina Nacional 6kg", stockCD: 0 },
      { name: "Nectarina USA", stockCD: 0 },
      { name: "Nespera", stockCD: 0 },
      { name: "Noni", stockCD: 0 },
      { name: "Pequi", stockCD: 0 },
      { name: "Pera Asiatica", stockCD: 0 },
      { name: "Pera Bosc", stockCD: 0 },
      { name: "Pera D'anjou", stockCD: 31 },
      { name: "Pera Ercolina", stockCD: 4 },
      { name: "Pera Forelle", stockCD: 0 },
      { name: "Pera Park", stockCD: 35 },
      { name: "Pera Park 1/2", stockCD: 0 },
      { name: "Pera Portuguesa", stockCD: 42 },
      { name: "Pera Portuguesa Band", stockCD: 0 },
      { name: "Pera Sacolinha", stockCD: 0 },
      { name: "Pera Vermelha", stockCD: 0 },
      { name: "Pera Willians", stockCD: 0 },
      { name: "Pera Willians 1/2", stockCD: 0 },
      { name: "Pessego 3Kg - 1 camada", stockCD: 0 },
      { name: "Pessego Amarelo", stockCD: 0 },
      { name: "Pessego Branco", stockCD: 0 },
      { name: "Pessego CP", stockCD: 0 },
      { name: "Pessego Dunits", stockCD: 0 },
      { name: "Pessego Importado", stockCD: 0 },
      { name: "Pessego Nacional 10kg - 2A", stockCD: 0 },
      { name: "Pessego Nacional 10kg - 3A", stockCD: 0 },
      { name: "Pessego Nacional 10kg - 4A", stockCD: 0 },
      { name: "Pessego Nacional 6kg", stockCD: 0 },
      { name: "Pessego USA", stockCD: 0 },
      { name: "Phisalis", stockCD: 0 },
      { name: "Pinha", stockCD: 5 },
      { name: "Pinhão", stockCD: 0 },
      { name: "Pitanga", stockCD: 0 },
      { name: "Pitaya", stockCD: 39 },
      { name: "Pitaya 3Kg", stockCD: 0 },
      { name: "Ranbutan", stockCD: 0 },
      { name: "Romã", stockCD: 0 },
      { name: "Romã Importado", stockCD: 7 },
      { name: "Sapoti", stockCD: 0 },
      { name: "Seriguela", stockCD: 0 },
      { name: "Tamarillo", stockCD: 0 },
      { name: "Tamarindo", stockCD: 0 },
      { name: "Tangerina Bergamota", stockCD: 0 },
      { name: "Tangerina Cravo", stockCD: 12 },
      { name: "Tangerina Decopon", stockCD: 0 },
      { name: "Tangerina Importada", stockCD: 0 },
      { name: "Tangerina Morgote", stockCD: 0 },
      { name: "Tangerina Morgote 1/2", stockCD: 0 },
      { name: "Tangerina Poncan", stockCD: 66 },
      { name: "Tangerina Poncan 1/2", stockCD: 0 },
      { name: "Tangerina Rio", stockCD: 3 },
      { name: "Tangerina Rio 9Kg", stockCD: 0 },
      { name: "Tangerina Verona s/ Sem.", stockCD: 34 },
      { name: "tangerina olé", stockCD: 26 },
      { name: "Umbu", stockCD: 0 },
      { name: "Uva Algodão Doce", stockCD: 17 },
      { name: "Uva Benetaka", stockCD: 0 },
      { name: "Uva Black / Morango", stockCD: 5 },
      { name: "Uva Brasil", stockCD: 0 },
      { name: "Uva Crinsom", stockCD: 0 },
      { name: "Uva Crinsom Band.", stockCD: 191 },
      { name: "Uva Doce Natural", stockCD: 0 },
      { name: "Uva Estela", stockCD: 72 },
      { name: "Uva Isis", stockCD: 0 },
      { name: "Uva Italia", stockCD: 0 },
      { name: "Uva Japonesa", stockCD: 0 },
      { name: "Uva mista", stockCD: 0 },
      { name: "Uva Moscatel", stockCD: 0 },
      { name: "Uva Nubia", stockCD: 0 },
      { name: "Uva Ouro", stockCD: 0 },
      { name: "Uva Pilar Moscato", stockCD: 0 },
      { name: "Uva Red Glob", stockCD: 0 },
      { name: "Uva Red Meire", stockCD: 0 },
      { name: "Uva Rosada 10kg", stockCD: 16 },
      { name: "Uva Rosada 5kg", stockCD: 0 },
      { name: "Uva Rosada Band", stockCD: 0 },
      { name: "Uva Rubi", stockCD: 0 },
      { name: "Uva Safira", stockCD: 0 },
      { name: "Uva Sta Isabel", stockCD: 0 },
      { name: "Uva Thompison", stockCD: 0 },
      { name: "Uva Thompison Band.", stockCD: 218 },
      { name: "Uva Vitoria", stockCD: 10 },
    ]
  },
  {
    category: "Legumes",
    products: [
      { name: "Abobora Baby", stockCD: 0 },
      { name: "Abobora p/ Doce", stockCD: 67 },
      { name: "Abobrinha Caipira", stockCD: 0 },
      { name: "Abobrinha Caipira G", stockCD: 0 },
      { name: "Abobrinha Clarita", stockCD: 0 },
      { name: "Abobrinha Italiana", stockCD: 11 },
      { name: "Abobrinha Menina", stockCD: 0 },
      { name: "Abobrinha Paulista", stockCD: 0 },
      { name: "Alcachofra", stockCD: 0 },
      { name: "Alcachofra Baby", stockCD: 0 },
      { name: "Alho Descascado", stockCD: 0 },
      { name: "Alho Roxo", stockCD: 214 },
      { name: "Batata Asterix", stockCD: 0 },
      { name: "Batata Binge", stockCD: 0 },
      { name: "Batata Cesar (Suja)", stockCD: 0 },
      { name: "Batata Doce 350grs c/20 (Trebeschi)", stockCD: 0 },
      { name: "Batata Doce Branca", stockCD: 0 },
      { name: "Batata Doce Roxa", stockCD: 0 },
      { name: "Batata Doce Salmon", stockCD: 0 },
      { name: "Batata Doce Vermelha", stockCD: 34 },
      { name: "Batata Monalisa", stockCD: 6 },
      { name: "Batata Pirulito", stockCD: 0 },
      { name: "Batata Primeirinha", stockCD: 0 },
      { name: "Batata Yacon", stockCD: 0 },
      { name: "Berinjela", stockCD: 0 },
      { name: "Berinjela Conserva", stockCD: 0 },
      { name: "Berinjela Japonesa", stockCD: 0 },
      { name: "Berinjela Media", stockCD: 0 },
      { name: "Berinjela Rajada", stockCD: 0 },
      { name: "Beterraba", stockCD: 21 },
      { name: "Beterraba Baby", stockCD: 0 },
      { name: "Beterraba Conserva", stockCD: 0 },
      { name: "Beterraba Cozida", stockCD: 0 },
      { name: "Beterraba Media", stockCD: 0 },
      { name: "Cabotia", stockCD: 180 },
      { name: "Cara", stockCD: 0 },
      { name: "Caxi", stockCD: 0 },
      { name: "Cebola Argentina", stockCD: 200 },
      { name: "Cebola Borbim", stockCD: 0 },
      { name: "Cebola Branca Import.", stockCD: 0 },
      { name: "Cebola Nacional", stockCD: 24 },
      { name: "Cebola Pirulito", stockCD: 0 },
      { name: "Cebola Roxa Import.", stockCD: 28 },
      { name: "Cenoura", stockCD: 20 },
      { name: "Cenoura Baby", stockCD: 0 },
      { name: "Cenoura Baby Monica", stockCD: 0 },
      { name: "Cenoura Gobo", stockCD: 0 },
      { name: "Cenoura Media", stockCD: 0 },
      { name: "Cenoura Rama", stockCD: 0 },
      { name: "Chuchu", stockCD: 56 },
      { name: "Ervilha Grão", stockCD: 0 },
      { name: "Ervilha Torta", stockCD: 0 },
      { name: "Feijão de Corda", stockCD: 0 },
      { name: "Gengibre", stockCD: 11 },
      { name: "Gengibre Miudo", stockCD: 0 },
      { name: "Gobo", stockCD: 0 },
      { name: "Inhame", stockCD: 8 },
      { name: "Inhame Miudo", stockCD: 0 },
      { name: "Jilo Branco", stockCD: 0 },
      { name: "Jilo Verde", stockCD: 0 },
      { name: "Mandioca Pct 1kg", stockCD: 0 },
      { name: "Mandioca com casca", stockCD: 0 },
      { name: "Mandioca cx", stockCD: 0 },
      { name: "Mandioca s/ Casca", stockCD: 375 },
      { name: "Mandioquinha Salsa", stockCD: 0 },
      { name: "Mandioquinha Salsa Media", stockCD: 0 },
      { name: "Maxixe", stockCD: 0 },
      { name: "Milho 450gr c/36 (Trebeschi)", stockCD: 0 },
      { name: "Milho Verde Band", stockCD: 300 },
      { name: "Milho Verde Saco", stockCD: 0 },
      { name: "milho doce", stockCD: 0 },
      { name: "Moranga", stockCD: 0 },
      { name: "Moranga Baby", stockCD: 0 },
      { name: "Mugango", stockCD: 0 },
      { name: "Pepino Baby", stockCD: 0 },
      { name: "Pepino Caipira", stockCD: 0 },
      { name: "Pepino Caipira Branco", stockCD: 0 },
      { name: "Pepino Conserva", stockCD: 8 },
      { name: "Pepino Conserva Medio", stockCD: 0 },
      { name: "Pimenta Americana", stockCD: 0 },
      { name: "Pimenta Ardida", stockCD: 0 },
      { name: "Pimenta Ardida 1/2", stockCD: 0 },
      { name: "Pimenta Biquinho", stockCD: 0 },
      { name: "Pimenta Cambuci", stockCD: 0 },
      { name: "Pimenta de Cheiro", stockCD: 0 },
      { name: "Pimenta Malagueta", stockCD: 0 },
      { name: "Pimenta Palermo", stockCD: 0 },
      { name: "Pimentas Diversas", stockCD: 0 },
      { name: "Pimentão Amarelo", stockCD: 14 },
      { name: "Pimentão Amarelo Medio", stockCD: 0 },
      { name: "Pimentão Creme/Laranja", stockCD: 0 },
      { name: "Pimentão Mesclado/Colorido", stockCD: 0 },
      { name: "Pimentão Rei", stockCD: 0 },
      { name: "Pimentão Verde", stockCD: 18 },
      { name: "Pimentão Verde Medio", stockCD: 0 },
      { name: "Pimentão Vermelho", stockCD: 7 },
      { name: "Pimentão Vermelho Medio", stockCD: 0 },
      { name: "Quiabo", stockCD: 0 },
      { name: "Quiabo Band", stockCD: 0 },
      { name: "Raiz Forte", stockCD: 0 },
      { name: "Repolho Roxo", stockCD: 4 },
      { name: "Repolho Verde", stockCD: 34 },
      { name: "Repolho Verde Medio", stockCD: 0 },
      { name: "Tomate Amarelo c/4", stockCD: 0 },
      { name: "Tomate Caqui PP", stockCD: 0 },
      { name: "Tomate Caqui cx Grande", stockCD: 0 },
      { name: "Tomate Cereja", stockCD: 0 },
      { name: "Tomate Cereja Band", stockCD: 0 },
      { name: "Tomate Cereja Rama 200gr c/46 (Trebeschi)", stockCD: 0 },
      { name: "Tomate Cereja c/4", stockCD: 0 },
      { name: "Tomate Coquetel 10kg", stockCD: 40 },
      { name: "Tomate Coquetel 15Kg", stockCD: 0 },
      { name: "Tomate Coquetel 5kg", stockCD: 0 },
      { name: "Tomate Grape 10kg", stockCD: 36 },
      { name: "Tomate Grape 20kg", stockCD: 0 },
      { name: "Tomate Grape Band", stockCD: 0 },
      { name: "Tomate Holandes", stockCD: 0 },
      { name: "Tomate Italiano", stockCD: 0 },
      { name: "Tomate Longa Vida", stockCD: 0 },
      { name: "Tomate Longa Vida Medio", stockCD: 0 },
      { name: "Tomate Mamotoro", stockCD: 0 },
      { name: "Tomate Pera/Perinha", stockCD: 0 },
      { name: "Tomate Pizzadoro", stockCD: 31 },
      { name: "Tomate Pizzadoro Medio", stockCD: 0 },
      { name: "Tomate Rasteiro", stockCD: 60 },
      { name: "Tomate Rasteiro Medio", stockCD: 0 },
      { name: "Tomate Romanita", stockCD: 0 },
      { name: "Tomate Salada", stockCD: 39 },
      { name: "Tomate Salada Medio", stockCD: null },
      { name: "Tomate Turma da Monica Uva 180gr c/60 (Trebeschi)", stockCD: 0 },
      { name: "Tomatinhos Confeites 250gr c/46 (Trebeschi)", stockCD: 0 },
      { name: "Vagem", stockCD: 0 },
      { name: "Vagem Manteiga", stockCD: 0 },
      { name: "Vagem Verdinha", stockCD: 0 },
    ]
  },
  {
    category: "Verduras",
    products: [
      { name: "Acelga", stockCD: 18 },
      { name: "Agriao Lavado", stockCD: 0 },
      { name: "Agrião Cx", stockCD: 0 },
      { name: "Agrião Hidroponico", stockCD: 0 },
      { name: "Alface Americana Band Hidro", stockCD: 0 },
      { name: "Alface Americana Lavada", stockCD: 0 },
      { name: "Alface Americana cx", stockCD: -8 },
      { name: "Alface Crespa Hidro Lavada", stockCD: 0 },
      { name: "Alface Crespa Hidro mç", stockCD: 0 },
      { name: "Alface Crespa cx", stockCD: 0 },
      { name: "Alface Crocante", stockCD: 0 },
      { name: "Alface Freelize cx", stockCD: 0 },
      { name: "Alface Frizzly Roxa mç", stockCD: 0 },
      { name: "Alface Frizzly Verde mç", stockCD: 0 },
      { name: "Alface Grega cx", stockCD: 0 },
      { name: "Alface Lisa Hidro Lavada", stockCD: 0 },
      { name: "Alface Lisa Hidro mç", stockCD: 0 },
      { name: "Alface Lisa cx", stockCD: 0 },
      { name: "Alface Mimosa Hidro mç", stockCD: 0 },
      { name: "Alface Mimosa Lavada", stockCD: 0 },
      { name: "Alface Mimosa cx", stockCD: 0 },
      { name: "Alface Romana Lavada", stockCD: 0 },
      { name: "Alface Romana cx", stockCD: 0 },
      { name: "Alface Romana mç", stockCD: 0 },
      { name: "Alface Roxa Hidro mç", stockCD: 0 },
      { name: "Alface Roxa Lavada", stockCD: 0 },
      { name: "Alface Roxa Mimosa Hidro mç", stockCD: 0 },
      { name: "Alface Roxa cx", stockCD: 0 },
      { name: "Alface Tricolor", stockCD: 0 },
      { name: "Alho Poro", stockCD: -3 },
      { name: "Almeirao Comum Lavado", stockCD: null },
      { name: "Almeirão Catalonia", stockCD: 0 },
      { name: "Almeirão Comum", stockCD: 0 },
      { name: "Almeirão Pão Açucar", stockCD: 0 },
      { name: "Brocolis Comum", stockCD: 0 },
      { name: "Brocolis Lavado", stockCD: 0 },
      { name: "Brocolis Ninja", stockCD: -20 },
      { name: "Cebolete", stockCD: 0 },
      { name: "Cebolinha", stockCD: -10 },
      { name: "Cebolinha Lavada", stockCD: 0 },
      { name: "Cheiro Verde", stockCD: 0 },
      { name: "Chicoria Lavada", stockCD: 0 },
      { name: "Chicoria cx", stockCD: 0 },
      { name: "Chicoria mç", stockCD: 0 },
      { name: "Coentro Ind.", stockCD: 0 },
      { name: "Coentro Lavado", stockCD: 0 },
      { name: "Coentro mç", stockCD: 0 },
      { name: "Couve Bruxelas", stockCD: 0 },
      { name: "Couve Flor", stockCD: 17 },
      { name: "Couve Flor Band", stockCD: 0 },
      { name: "Couve Flor Roxa", stockCD: 0 },
      { name: "Couve Kale", stockCD: 0 },
      { name: "Couve Lavada", stockCD: 0 },
      { name: "Couve Rabano", stockCD: 0 },
      { name: "Couve cx", stockCD: 0 },
      { name: "Couve mç", stockCD: 0 },
      { name: "Erva Doce", stockCD: 0 },
      { name: "Espinafre Lavado", stockCD: 0 },
      { name: "Espinafre cx", stockCD: 0 },
      { name: "Espinafre mç", stockCD: 0 },
      { name: "Folha Beterraba", stockCD: 0 },
      { name: "Folha de Cenoura", stockCD: 0 },
      { name: "Hanna Nira", stockCD: 0 },
      { name: "Hortela Ind.", stockCD: 0 },
      { name: "Hortela Kibe", stockCD: 0 },
      { name: "Hortela Lavado", stockCD: 0 },
      { name: "Hortela Levante", stockCD: 0 },
      { name: "Hortela mç", stockCD: -26 },
      { name: "Hortelã Kg", stockCD: 0 },
      { name: "Mini Crespa", stockCD: 0 },
      { name: "Mini Lisa", stockCD: 0 },
      { name: "Mini Mimosa", stockCD: 0 },
      { name: "Mini Romana", stockCD: 0 },
      { name: "Mizuna", stockCD: 0 },
      { name: "Mostarda", stockCD: 0 },
      { name: "Nabo", stockCD: 0 },
      { name: "Nabo Frances", stockCD: 0 },
      { name: "Nabo Redondo", stockCD: 0 },
      { name: "Nirá", stockCD: 0 },
      { name: "Rabanete", stockCD: 0 },
      { name: "Radiche", stockCD: 0 },
      { name: "Rucula", stockCD: -220 },
      { name: "Rucula Baby", stockCD: 0 },
      { name: "Rucula Lavada", stockCD: 0 },
      { name: "Rucula Selvatica", stockCD: 0 },
      { name: "Rucula cx", stockCD: 0 },
      { name: "Salsa", stockCD: -8 },
      { name: "Salsa Crespa", stockCD: 0 },
      { name: "Salsa Lavada", stockCD: 0 },
      { name: "Salsão", stockCD: 0 },
      { name: "Taioba", stockCD: 0 },
      { name: "Tinguensai / Pakoshoy", stockCD: 0 },
    ]
  },
  {
    category: "Ervas e Especiais",
    products: [
      { name: "Açafrão", stockCD: 0 },
      { name: "Aipo", stockCD: 0 },
      { name: "Alecrim", stockCD: 0 },
      { name: "Alecrim Kg", stockCD: 0 },
      { name: "Alfafa", stockCD: 0 },
      { name: "Alfavaca", stockCD: 0 },
      { name: "Arnica", stockCD: 0 },
      { name: "Arruda", stockCD: 0 },
      { name: "Basilicão", stockCD: 0 },
      { name: "Boldo", stockCD: 0 },
      { name: "Buscopan", stockCD: 0 },
      { name: "Canfora", stockCD: 0 },
      { name: "Capim Cidreira", stockCD: 0 },
      { name: "Capim Santo", stockCD: 0 },
      { name: "Carqueija", stockCD: 0 },
      { name: "Cidreira", stockCD: 0 },
      { name: "Citronela", stockCD: 0 },
      { name: "Cominho", stockCD: 0 },
      { name: "Dill", stockCD: 0 },
      { name: "Erva Sta Maria", stockCD: 0 },
      { name: "Ervas", stockCD: 0 },
      { name: "Estragão", stockCD: 0 },
      { name: "Flor Comestivel", stockCD: 0 },
      { name: "Folha de Graviola", stockCD: 0 },
      { name: "Folha de Uva", stockCD: 0 },
      { name: "Guaco", stockCD: 0 },
      { name: "Horenzzo", stockCD: 0 },
      { name: "Louro", stockCD: 0 },
      { name: "Manjericão", stockCD: 0 },
      { name: "Manjericão Kg", stockCD: 0 },
      { name: "Manjericão Roxo", stockCD: 0 },
      { name: "Manjerona", stockCD: 0 },
      { name: "Mastruz", stockCD: 0 },
      { name: "Melissa", stockCD: 0 },
      { name: "Menta", stockCD: 0 },
      { name: "Oregano", stockCD: 0 },
      { name: "Peixinho", stockCD: 0 },
      { name: "Poejo", stockCD: 0 },
      { name: "Por Nobe", stockCD: 0 },
      { name: "Salvia", stockCD: 0 },
      { name: "Tomilho", stockCD: 0 },
      { name: "Tomilho Kg", stockCD: 0 },
      { name: "Tomilho Limão", stockCD: 0 },
      { name: "Vick", stockCD: 0 },
    ]
  },
  {
    category: "Diversos",
    products: [
      { name: "Aspargo", stockCD: 0 },
      { name: "Aspargo Branco", stockCD: 0 },
      { name: "Bandejados Pré Processados", stockCD: 0 },
      { name: "Broto Bambu / Takenoko", stockCD: 0 },
      { name: "Cog. Shitake", stockCD: 0 },
      { name: "Cog.Shimeji Amarelo", stockCD: 0 },
      { name: "Cog.Shimeji Branco", stockCD: 0 },
      { name: "Cog.Shimeji Fatiado", stockCD: 0 },
      { name: "Cog.Shimeji Preto", stockCD: 0 },
      { name: "Cogumelo Ering", stockCD: 0 },
      { name: "Cogumelo Hiratak", stockCD: 0 },
      { name: "Cogumelo Mix", stockCD: 0 },
      { name: "Cogumelo Paris", stockCD: 0 },
      { name: "Cogumelo Paris Fatiado", stockCD: 0 },
      { name: "Cogumelo Porto Belo", stockCD: 0 },
      { name: "Cogumelo Porto Belo Fatiado", stockCD: 0 },
      { name: "Cogumelo Salmão", stockCD: 0 },
      { name: "Endivia", stockCD: 0 },
      { name: "Endivia Roxa", stockCD: 0 },
      { name: "Lenha", stockCD: 0 },
      { name: "Moyashi G", stockCD: 0 },
      { name: "Moyashi M", stockCD: 0 },
      { name: "Palmito Pupunha", stockCD: 0 },
      { name: "Terra Adubada", stockCD: 0 },
      { name: "Tofu", stockCD: 0 },
      { name: "Transf Lojas P/ Marrone-Eduardo", stockCD: 0 },
    ]
  }
]

async function safeDelete(table: () => Promise<unknown>) {
  try { await table() } catch (e: unknown) {
    if (e instanceof Error && e.message.includes('does not exist')) {
      console.warn(`  Table not found, skipping: ${e.message.split('\n')[0]}`)
    } else { throw e }
  }
}

async function main() {
  console.log('Seed started...')

  const adminUsername = 'admin'
  const supervisorUsername = 'supervisor'

  await safeDelete(() => prisma.stockCountItem.deleteMany({}))
  await safeDelete(() => prisma.stockCount.deleteMany({}))
  await safeDelete(() => prisma.stockMovement.deleteMany({}))
  await safeDelete(() => prisma.purchaseOrderItem.deleteMany({}))
  await safeDelete(() => prisma.purchaseOrder.deleteMany({}))
  await safeDelete(() => prisma.supplier.deleteMany({}))
  await safeDelete(() => prisma.orderItem.deleteMany({}))
  await safeDelete(() => prisma.order.deleteMany({}))
  await prisma.product.deleteMany({})
  await prisma.category.deleteMany({})
  await prisma.user.deleteMany({ where: { OR: [{ username: adminUsername }, { username: supervisorUsername }] } })
  await prisma.store.deleteMany({})

  const ceasas = [
    { name: "CEASA I", type: "CEASA", address: "" },
    { name: "CEASA II", type: "CEASA", address: "" },
    { name: "CEASA III", type: "CEASA", address: "" },
    { name: "CEASA IV", type: "CEASA", address: "" },
    { name: "CEASA V", type: "CEASA", address: "" },
  ]
  for (const c of ceasas) {
    await prisma.supplier.create({ data: c })
  }
  console.log(`Created ${ceasas.length} CEASA suppliers`)

  const createdStores = []
  for (const s of storesData) {
    const store = await prisma.store.create({ data: s })
    createdStores.push(store)
  }
  console.log(`Created ${createdStores.length} stores`)

  const hashedPassword = await bcrypt.hash('admin123', 10)
  const admin = await prisma.user.create({
    data: {
      username: adminUsername,
      name: 'Admin',
      email: 'admin@admin.com',
      password: hashedPassword,
      role: 'ADMIN',
      stores: { connect: createdStores.map(s => ({ id: s.id })) }
    }
  })
  console.log('Admin user created with role ADMIN')

  const hashedSupervisorPassword = await bcrypt.hash('supervisor123', 10)
  const supervisor = await prisma.user.create({
    data: {
      username: supervisorUsername,
      name: 'Supervisor',
      email: 'supervisor@supervisor.com',
      password: hashedSupervisorPassword,
      role: 'SUPERVISOR',
      stores: { connect: createdStores.map(s => ({ id: s.id })) }
    }
  })
  console.log('Supervisor user created with role SUPERVISOR')

  let total = 0
  for (const item of productCategories) {
    const category = await prisma.category.create({ data: { name: item.category } })
    console.log(`Category created: ${category.name}`)

    for (const product of item.products) {
      await prisma.product.create({
        data: {
          name: product.name,
          price: 0,
          stock: 0,
          stockCD: product.stockCD ?? null,
          categoryId: category.id,
          userId: admin.id
        }
      })
      total++
    }
    console.log(`Inserted ${item.products.length} products for ${item.category}`)
  }
  console.log(`Total products inserted: ${total}`)

  console.log('Seed finished successfully.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
